overrides:
  xmldom@<0.5.0: '>=0.5.0'
  node-fetch@<2.6.7: '>=2.6.7'
  trim-newlines@<3.0.1: '>=3.0.1'
  plist@<3.0.5: '>=3.0.5'
  nth-check@<2.0.1: '>=2.0.1'
  semver@>=7.0.0 <7.5.2: '>=7.5.2'
  semver@<5.7.2: '>=5.7.2'
  '@babel/runtime@<7.26.10': '>=7.26.10'
  cross-spawn@<6.0.6: '>=6.0.6'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
